### ISSUE TITLE
dark theme Main font color problem

### ISSUE THREAD

**Issue by henices** [vipzhicheng/logseq-plugin-google-fonts#1]
When using Logseq google fonts plugin, switch to dark theme the main font color remain default RGB 000 

![image](https://user-images.githubusercontent.com/929715/178430532-2f83e22b-88a1-4569-87cc-844d4798b5b9.png)

disable Logseq google fonts plugin

![image](https://user-images.githubusercontent.com/929715/178430610-10809826-2c78-40ee-821d-92ad826631e3.png)

**Comment by vipzhicheng** [comment]
Will be fixed in the next release.

**Comment by henices** [comment]
https://github.com/vipzhicheng/logseq-plugin-google-fonts/commit/ff7a039fce1317ed520d0f8c4e9c9e098881e73f
